apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse-main
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      host: ${CLICKHOUSE_HOST}
      port: ${CLICKHOUSE_PORT}
      protocol: native
      secure: false
      username: ${CLICKHOUSE_USERNAME}
      defaultDatabase: ${CLICKHOUSE_DATABASE}
      dialTimeout: 10
      queryTimeout: 60
      validateSql: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
